config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  #bookmark.movie
  belongs_to :list
  #bookmark.list

  validates :comment, presence: true
  validates :comment, length: {minimum: 6}
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :list, through: :bookmarks
  has_many :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)

    if @bookmark.save
      redirect_to lists_path(@list), notice: 'Bookmark was successfully added.'
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to lists_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    # No need for app/views/restaurants/create.html.erb
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

    def destroy
      @list = List.find(params[:id])
      @list.destroy
      # No need for app/views/restaurants/destroy.html.erb
      redirect_to lists_path, status: :see_other
    end


  private

  def list_params
    params.require(:list).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= bookmark.comment %></li>
  <% end %>
</ul>

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie_id, collection: Movie.all, label: 'Select a movie' %>
  <%= f.input :comment %>
  <%= f.submit 'Add Bookmark' %>

<% end %>
<%= console %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to(list.name, list_path(list)) %></li>
  <% end %>
</ul>

<%= link_to("CREAR LISTA", new_list_path ) %>

app/views/lists/new.html.erb
<%= form_with model: @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<%= link_to "Eliminar esta lista",
  list_path(@list),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

<%= link_to("Crear un Bookmark",  new_list_bookmark_path(@list)) %>


<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= bookmark.comment %></li>
     <li><%= image_tag bookmark.movie.poster_url %></li>
<%= link_to "Eliminar",
  bookmark_path(bookmark),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
  <% end %>
</ul>



<%
=begin%>
 <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie_id, collection: Movie.all, label: 'Select a movie' %>
  <%= f.submit 'Add Bookmark' %>
<% end %>

<%
=end%>